environment:

  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python311"
    - PYTHON: "C:\\Python311-x64"

init:
  - "echo Testing with %PYTHON%"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  - "%PYTHON%\\Scripts\\spec.exe"
