[tool.mypy]
# check_untyped_defs = true
# follow_imports_for_stubs = true
# disallow_any_decorated = true
# disallow_any_generics = true
# disallow_any_unimported = true
# disallow_incomplete_defs = true
# disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_untyped_decorators = true
disallow_untyped_defs = true
# enable_error_code = redundant-expr, truthy-bool, ignore-without-code, unused-awaitable
# implicit_reexport = False
exclude = [
    "integration/", "tests/", "setup.py", "tasks.py", "sites/www/conf.py"
]
ignore_missing_imports = true
# no_implicit_optional = true
# pretty = true
# show_column_numbers = true
# show_error_codes = true
# strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
# warn_return_any = true
# warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "invoke.vendor.*"
ignore_errors = true

# [[tool.mypy.overrides]]
# module = "mypy-tests.*"
# disallow_any_decorated = False
# disallow_untyped_calls = False
# disallow_untyped_defs = False
