version: 2.1


orbs:
  orb: invocations/orb@1.1.0


jobs:
  # Unit+integration tests, with coverage
  coverage:
    executor:
      name: orb/default
      version: "3.6"
    steps:
      - orb/setup
      - run: inv ci.make-sudouser
      # Split up coverage generation (under sudo for integration suite) and
      # compiling/uploading (wants to be as main user)
      - run: inv ci.sudo-run 'inv coverage'
      - run: coverage xml
      - run: codecov
      - orb/debug

  regression:
    executor:
      name: orb/default
      version: "3.6"
    steps:
      - orb/setup
      - run: inv regression
      - orb/debug

  doctests:
    executor:
      name: orb/default
      version: "3.6"
    steps:
      - orb/setup
      - run: inv www.doctest
      - orb/debug


workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - coverage:
          name: Test 3.6
      - regression:
          name: Regression tests
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test 3.6"]
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9"]
      - orb/docs:
          name: "Docs"
          requires: ["Test 3.6"]
      - doctests:
          name: "Doctests"
          requires: ["Docs"]
